# Conexión PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/cacao_db
spring.datasource.username=postgres
spring.datasource.password=Doctora2025

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Puerto del servidor
server.port=8080